name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnows"
database_id = "3e677c3a-0cf6-40cb-b69a-908c91f08d67"
